name: CI
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          # - arm64
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Build the ESPHome binary
        uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: FunHouse.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: FunHouse-${{ steps.esphome-build.outputs.name }}
          path: ${{ steps.esphome-build.outputs.name }}
